# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Overall Meta Data
title: Karan Jayachandra
email: mail@karanjayachandra.com
description: >- # this means to ignore newlines until "baseurl:"
  Karan's Website
domain: www.karanjayachandra.com
url: https://www.karanjayachandra.com
logo: /assets/logo.png
favicon: /assets/title.png

# Build Theme and Settings
remote_theme: MrKaranJ/jekyll-theme-console
style: light

# Required Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# List of pages for the Nav Bar
header_pages:
  - home/index.md
  - cv/index.md
  - blog/index.md

# Theme Variables
footer: '<a href="https://t.me/MrKaranJ">Message</a> \t <a href="mailto:mail@karanjayachandra.com">Email</a> \t <a href="https://www.linkedin.com/in/mrkaranj/">LinkedIn</a> \t <a href="https://github.com/MrKaranJ">GitHub</a>'