# Overall Meta Data
title: Karan Jayachandra
email: mail@karanjayachandra.com
description: Karan's Website
domain: www.karanjayachandra.com
url: https://www.karanjayachandra.com
logo: /assets/logo.png
favicon: /assets/title.png
jekyll_baseurl: karanjayachandra.com

# Build Theme and Settings
remote_theme: KaranJayachandra/jekyll-theme-console
style: light

# Required Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-spaceship

# List of pages for the Nav Bar
header_pages:
  - home/index.md
  - cv/index.md
  - blog/index.md

# Use the Mathjax Processor from Spaceship
jekyll-spaceship:
  processors:
    - mathjax-processor